### ISSUE TITLE
Building on a non-RHEL host

### ISSUE THREAD

**Issue by jmtd** [rh-openjdk/redhat-openjdk-containers#128]
Related to #57 but i decided against  co-opting that particular issue

Some notes

cekit needs odcs-client which needs libkrb5-dev (gssapi.h) even if odcs stuff is not defined in the YAMLs.

The image FROM names are not obviously resolveable, e.g.
`ubi8-minimal:8-released` needs to be mapped to `registry.access.redhat.com/ubi8/ubi-minimal:latest`. The simplest solution is to locally tag the image e.g.

    podman tag registry.access.redhat.com/ubi8/ubi-minimal:latest ubi8-minimal:8-released

later

```
Error: Problems in request:
missing groups or modules: maven:3.6
```

Could the maven packages not have made it into the UBI set? Or local network issues here

**Comment by jerboaa** [comment]
@jmtd Nice find!

**Comment by jmtd** [comment]
Resolved. I've just successfully built ubi8-openjdk-8 from a Debian host. (also the CI does it from Ubuntu)
