### ISSUE TITLE
openshift openjdk8 imagestreams reference images which are now invalid

### ISSUE THREAD

**Issue by gabemontero** [rh-openjdk/redhat-openjdk-containers#200]
hey @jmtd 

In case you check github jira issues more closely than bugzillas :-) I'm opening this to alert you to a problem with the openjdk8 imagestream for openshift 

All the gory details are in https://bugzilla.redhat.com/show_bug.cgi?id=1946663

fyi I had to open a BZ instead of a jira so I can mark an openshift bz I have "officially" dependent / blocked by the changes we need on your end

thanks

**Comment by jmtd** [comment]
Thanks @gabemontero looks like we've resolved it now.
