### ISSUE TITLE
Make run-java.sh support Quarkus

### ISSUE THREAD

**Issue by quintesse** [rh-openjdk/redhat-openjdk-containers#206]
It would be useful if the script would by default understand Quarkus apps.

I think the "uber-jar" build layout already works (but it would have to be tested to be sure), but the other two layouts are not. The "legacy-jar" one always creates two jars (one xxx.jar and one xxx-runner.jar, it's the latter that's needed) plus a lib folder, while the new "fast-jar" option creates an entire folder with a bunch of files (including the dependencies in a lib folder and even a third jar with the fixed name quarkus-app.jar).

**Comment by jmtd** [comment]
Resolved in  #358.
