### ISSUE TITLE
Invalid JAVA_HOME in runtime image

### ISSUE THREAD

**Issue by jfdenise** [rh-openjdk/redhat-openjdk-containers#219]
I am creating my own image from registry.access.redhat.com/ubi8/openjdk-11-runtime
I notice that the JAVA_HOME env variable points to /usr/lib/jvm/java-11 (https://github.com/jboss-container-images/openjdk/blob/develop/modules/jre/11/module.yaml#L17) that doesn't exist in the image.

**Comment by jerboaa** [comment]
Thanks! See #214
