### ISSUE TITLE
runnable openjdk-11-runtime image

### ISSUE THREAD

**Issue by jfdenise** [rh-openjdk/redhat-openjdk-containers#220]
Inside a chained build, I was expecting to only have to copy a bootable JAR into the runtime image /deployments directory then have the run script to take over on image run and start my app with correct JVM settings.
Instead it is displaying the message:  "This is the Red Hat UBI8 OpenJDK 11 Runtime container".
I am wandering if the runtime image could take advantages of the automatic (and configurable) JVM configuration we find in the builder image and offer an entry point that would automatically run/configure a java application?
Thank-you.

**Comment by jmtd** [comment]
Hi @jfdenise 

>  I am wandering if the runtime image could take advantages of the automatic (and configurable) JVM configuration we find in the builder image and offer an entry point that would automatically run/configure a java application?

Yes this is a limitation. We decided against including the existing `run-java.sh` in the runtime image for launch, as we need to go through it and make sure it is not too tightly coupled to maven, etc., which are not going to be present. That should happen but we didn't want to delay releasing something in the meantime.

**Comment by jfdenise** [comment]
@jmtd , thank-you, makes full sense. So I understand that the long term plan is to have a runnable runtime-image.

**Comment by jmtd** [comment]
I've filed https://issues.redhat.com/browse/OPENJDK-413 to track this on the product  side.

**Comment by jmtd** [comment]
Addressed from 1.12 onwards
