### ISSUE TITLE
Provide image with newer JDK

### ISSUE THREAD

**Issue by ibotty** [rh-openjdk/redhat-openjdk-containers#235]
The released images I could find are jdk 11. AFAICT the newer ubi8-based builders are also based on jdk 11. Is it possible to use a newer jdk?

**Comment by jerboaa** [comment]
The next LTS version of OpenJDK is going to be JDK 17 which is expected to be generally available in September 2021. There is a plan to provide UBI images with JDK 17 at that point. There are no plans to include any STS versions, like JDK 16.

**Comment by ibotty** [comment]
Thank you for your answer.
