### ISSUE TITLE
Add OpenJDK 17 images to OpenShift ImageStream templates

### ISSUE THREAD

**Issue by jmtd** [rh-openjdk/redhat-openjdk-containers#243]
We need to add entries for OpenJDK 17 to the following template files in templates/:
```
"community-image-streams.json"
"image-streams-aarch64.json"
"image-streams.json"
"image-streams-ppc64le.json"
"image-streams-s390x.json"
"openjdk-web-basic-s2i.json"
"openjdk-web-basic-s2i.json.orig"
"runtime-image-streams.json"
```
These changes need to target the `release` branch, in order for the scripts in https://github.com/openshift/library to pull in the changes.
The changed files can be tested by
1. syntax checking by running through a tool like `jq`,
2. importing them into an OpenShift cluster,
3. running the `make import`, `make verify` steps from a clone of https://github.com/openshift/library which has been adjusted to pull the templates from a development fork/branch.

**Comment by jhuttana** [comment]
> We need to add entries for OpenJDK 17 to the following template files in templates/:
> 
> ```
> "community-image-streams.json"
> "image-streams-aarch64.json"
> "image-streams.json"
> "image-streams-ppc64le.json"
> "image-streams-s390x.json"
> "openjdk-web-basic-s2i.json"
> "openjdk-web-basic-s2i.json.orig"
> "runtime-image-streams.json"
> ```
> 
> These changes need to target the `release` branch, in order for the scripts in https://github.com/openshift/library to pull in the changes. The changed files can be tested by

Here targeting release branch is confusing me ;) 
Ideally branching from 'develop' branch and making changes what I followed. Do you mean for this we need to branch from 'release' branch ? If yes, then I don't see JDK17 related descriptors (ubi8-openjdk-17.yaml and ubi8-openjdk-17-runtime.yaml) on release branch.
Could you please elaborate it further?

> 
>     1. syntax checking by running through a tool like `jq`,
> 
>     2. importing them into an OpenShift cluster,
> 
>     3. running the `make import`, `make verify` steps from a clone of https://github.com/openshift/library which has been adjusted to pull the templates from a development fork/branch.

**Comment by pestapever** [comment]
I used to create a Quarkus app for openshift S2I strategy with command "oc new-app openjdk-11-rhel7 ...", with ubi I got problems.. I'm waiting for a jdk17rhel to upgrade java version with new applications..

**Comment by jmtd** [comment]
This was completed in https://github.com/jboss-container-images/openjdk/pull/269
