### ISSUE TITLE
s2i binary build failure using openj9/openj9-11-rhel8

### ISSUE THREAD

**Issue by iocanel** [rh-openjdk/redhat-openjdk-containers#249]
I tried using `openj9/openj9-11-rhel8` instead of the `registry.access.redhat.com/ubi8/openjdk-11` for s2i binary build and go the error below:

`error: build error: error building at STEP "RUN chown -R 185:0 /tmp/src": error while running runtime: exit status 1`

I get this behavior in a `quarkus` project that uses the `quarkus-openshift` extension for generating the `BuildConfig` and initiating the build. As mentioned above everything works fine with images like the `registry.access.redhat.com/ubi8/openjdk-11` but fails with using `openj9/openj9-11-rhel8`

**Comment by jerboaa** [comment]
> `error: build error: error building at STEP "RUN chown -R 185:0 /tmp/src": error while running runtime: exit status 1`

Paging @levivic to have a look at this. Thanks!

**Comment by levivic** [comment]
Circling back to https://issues.redhat.com/browse/QUARKUS-1352

**Comment by jmtd** [comment]
closing (forwarded to QUARKUS-1352)
