### ISSUE TITLE
Add GHA tests for ubi8/openjdk-17

### ISSUE THREAD

**Issue by jerboaa** [rh-openjdk/redhat-openjdk-containers#253]
Currently only JDK 8 and 11 behave tests run via GHA. Adding OpenJDK 17 tests would be great to have.

**Comment by jmtd** [comment]
This might be another good issue for @jhuttana

**Comment by jhuttana** [comment]
Ok :) Could you guys please point some examples?

**Comment by jerboaa** [comment]
https://github.com/jboss-container-images/openjdk/blob/develop/.github/workflows/ubi8-openjdk-11.yml

Is the workflow file for the `ubi8/openjdk11` image. The rest is plain Github Actions doc.

**Comment by jhuttana** [comment]
> https://github.com/jboss-container-images/openjdk/blob/develop/.github/workflows/ubi8-openjdk-11.yml
> 
> Is the workflow file for the `ubi8/openjdk11` image. The rest is plain Github Actions doc.


Ok Thank you!
