### ISSUE TITLE
singleton-jdk configure.sh shouldn't fail if no packages are to be removed

### ISSUE THREAD

**Issue by jfdenise** [rh-openjdk/redhat-openjdk-containers#268]
I am in a context in which I am building a JDK11 based image + maven. JDK11 only is installed. The singleton-jdk module configure.sh fails with error:
"rpm: no packages given for erase".
Trying to build https://github.com/jboss-container-images/openjdk/blob/develop/ubi8-openjdk-11.yaml shows the same problem.

Could we disable (set +e) error and allow for no packages to erase?

**Comment by jmtd** [comment]
Hi @jfdenise , the point of that module is for when you purposefully have to install more than one JDK due to RPM package dependencies and then need to remove all but the desired one at the end. If you don't have to install multiple JDKs, you can remove the singleton-jdk module from your module list. Am I missing something?

**Comment by jfdenise** [comment]
@jmtd , yes not adding the module is a solution. I was surprised to see it in openjdk-11 image that does contain a single JDK: https://github.com/jboss-container-images/openjdk/blob/develop/ubi8-openjdk-11.yaml#L53

**Comment by jmtd** [comment]
[sadly it was still necessary](https://github.com/jboss-container-images/openjdk/commit/d141578dcc882a19db7fb286f1dd168f298f022e), I wish I wrote why in that commit. I think it's one of the agent RPMs. It might not be any more!

**Comment by jerboaa** [comment]
> [sadly it was still necessary](https://github.com/jboss-container-images/openjdk/commit/d141578dcc882a19db7fb286f1dd168f298f022e), I wish I wrote why in that commit. I think it's one of the agent RPMs. It might not be any more!

https://bugzilla.redhat.com/show_bug.cgi?id=1910354 ?

**Comment by jmtd** [comment]
That'll be it, yes. Thanks!
