### ISSUE TITLE
How to subscribe to notifications of new image release? 

### ISSUE THREAD

**Issue by TiloGit** [rh-openjdk/redhat-openjdk-containers#334]
How can we subscribe to notification for new image release? 
Watch this GH repo seem not be enough.

We would like to notification if a new Image is available (due to Java or ubi update)

e.g. if we get a new Image of `OpenJDK 17 runtime image on UBI9` like `1.13-9.1669632204` how could we get notified?

**Comment by jerboaa** [comment]
@TiloGit Is there a good reason to not use the latest `ubi9/openjdk-17:latest` image? That way you'll always get the most up-to-date build (including security fixes in OpenJDK).

**Comment by TiloGit** [comment]
@jerboaa  thanks for the quick reply. yes we use latest tag. 
We build FROM `ubi9/openjdk-17:latest` so we would like to be able to trigger our build based on upstream update image. 

That is why I ask for what type of notification we could get for new release of `ubi9/openjdk-17`

**Comment by jerboaa** [comment]
OK. I'm not aware of any image update push notifications. If you were on OpenShift, that would be handled by the image stream triggers. https://docs.openshift.com/container-platform/4.10/openshift_images/triggering-updates-on-imagestream-changes.html

**Comment by TiloGit** [comment]
fyi, for now I run a daily GH action for our project to compare the hash, if the hash changes we trigger a build of our images : 
```bash
upstreamRepo='registry.access.redhat.com'
upstreamImage='ubi9/openjdk-17-runtime'
curl --silent -L  --header "Accept: application/vnd.docker.distribution.manifest.v2+json" "https://$upstreamRepo/v2/$upstreamImage/manifests/latest" |     jq -r '.config.digest'
```

**Comment by jmtd** [comment]
@TiloGit I'm starting to push tags for new image updates: see e.g. https://github.com/jboss-container-images/openjdk/releases/tag/ubi8-openjdk-containers-1.16 and https://github.com/jboss-container-images/openjdk/releases/tag/ubi9-openjdk-containers-1.15 . I think GitHub might provide a means to watch for new tags. You can expect roughly 4 releases a year, spaced out roughly March/June/August/November

However this will only cover minor or major version bumps, not micro -- which we use for respins -- which don't have source-level changes, and so this repo doesn't change for those; but are also important. At the least they cover the OpenJDK Critical Patch Updates (CPUs): the images pick up newer RPMs , but also any other CVE fixes.
