### ISSUE TITLE
MAVEN_ARGS is known by mvn starting 3.9

### ISSUE THREAD

**Issue by jfdenise** [rh-openjdk/redhat-openjdk-containers#343]
As we can see there: https://issues.apache.org/jira/browse/MNG-7193 MAVEN_ARGS is natively supported by maven 3.9
Thia has an impact on s2i. This line for example: https://github.com/jboss-container-images/openjdk/blob/ubi8/modules/maven/default/artifacts/opt/jboss/container/maven/default/maven.sh#L85 would have to be modified to not set $MAVEN_ARGS in the command line (it would duplicate the args).

**Comment by jmtd** [comment]
Oh boy this is going to be interesting. Thanks for raising this. I've got a couple of thoughts about how we address this (and mitigate any similar problems down the road), I'll raise it on the Middleware Containers list to get a wider audience.

**Comment by jmtd** [comment]
Resolved by #372 and #348.
