### ISSUE TITLE
GA actions use deprecated ubuntu version

### ISSUE THREAD

**Issue by jmtd** [rh-openjdk/redhat-openjdk-containers#350]
Perhaps not coincidentally we seem to have a problem with timely running of actions

**Comment by jerboaa** [comment]
Can't we not just switch to 22.04 runners?

**Comment by jmtd** [comment]
> Can't we not just switch to 22.04 runners?

Yes probably. I don't know if any other changes would be needed. Easiest way to find out is to switch and see what breaks!

**Comment by jmtd** [comment]
reopening until resolved for ubi8 too

**Comment by jmtd** [comment]
UBI8 updated now too.
