### ISSUE TITLE
[Q] How to check version detail of running container? 

### ISSUE THREAD

**Issue by TiloGit** [rh-openjdk/redhat-openjdk-containers#362]
Hi, 

does the **running** container contain any info about the version? (looking for `1.1687182770` or `1.16-1.1687182770` or build date `2023-06-19T14:12:15`

The container labels have these (but can't view them on kubectl)
```console
core@DEVCoreOS14 ~ $ docker inspect registry.access.redhat.com/ubi8/openjdk-17-runtime  | jq '.[] | .Created, .Config.Labels'
"2023-06-19T14:31:13.723295584Z"
```
```json
{
  "architecture": "x86_64",
  "build-date": "2023-06-19T14:12:15",
...
  "io.buildah.version": "1.29.0",
  "io.cekit.version": "4.7.0",
...
  "release": "1.1687182770",
  "summary": "Image for Red Hat OpenShift providing OpenJDK 17 runtime",
  "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/openjdk-17-runtime/images/1.16-1.1687182770",
  "vcs-ref": "3aa842acd0430ce1e0a6ba3219d036dd6ec6337b",
  "version": "1.16"
}
```

The `/etc/os-release` doesn't seem to have that level of details about the version. 
```console
[root@myCont123]# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
```

Maybe an UBI upstream question but I will start here :-)

**Comment by jerboaa** [comment]
For the OpenJDK image the version info is `<version>-<release>` from the labels as you've noted:

```
{
  "architecture": "x86_64",
  "build-date": "2023-06-19T14:12:15",
...
  "io.buildah.version": "1.29.0",
  "io.cekit.version": "4.7.0",
...
  "release": "1.1687182770",
  "summary": "Image for Red Hat OpenShift providing OpenJDK 17 runtime",
  "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/openjdk-17-runtime/images/1.16-1.1687182770",
  "vcs-ref": "3aa842acd0430ce1e0a6ba3219d036dd6ec6337b",
  "version": "1.16"
}
```

=> `1.16-1.1687182770`. That's also the tag in the registry. AFAIK, @jmtd  also to tags respective versions in the repo as well. `1.16` in this case: https://github.com/jboss-container-images/openjdk/releases/tag/ubi8-openjdk-containers-1.16 so as to map this to the source level.

HTH.

**Comment by jerboaa** [comment]
At runtime it's the `JBOSS_IMAGE_VERSION` env AFAIK:

$ podman run --rm -ti --entrypoint /bin/bash registry.access.redhat.com/ubi8/openjdk-17-runtime -c 'env | grep JBOSS_IMAGE_VERSION'
JBOSS_IMAGE_VERSION=1.16

**Comment by TiloGit** [comment]
Thanks for the reply @jerboaa 

`JBOSS_IMAGE_VERSION` env variable show the version but not the release. 

any idea how to find the **release number** or **build date** of the running container?  `1.16-1.1687182770`

**Comment by jmtd** [comment]
HI: as you note, the labels have it (the `release` and `url` labels); in the container metadata its also in "RepoTags" I think (from `docker inspect`). The tricky thing for us (image maintainers) is we don't specify that label manually, it's added by our build infrastructure downstream from us, so we don't have visibility of the release number (or build date) at the image sources.

I'm not too familiar with `kubectl` (I work mostly with OpenShift layered on top of k8s and not k8s on its own). It seems like a limitation of kubectl if you can't use it to query an image's labels.

With OpenShift, something like the following works

```
$ oc import-image jdowland-test-img --from=registry.access.redhat.com/ubi9/openjdk-11:1.15 --confirm
$ oc get -o json  ImageStreamTag/jdowland-test-img:latest \
     | jq - .image.dockerImageMetadata.Config.Labels.release
```

**Comment by TiloGit** [comment]
found it:  **/root/buildinfo/**

```console
[jboss@2746c3b882d6 ~]$ ls -ls /root/buildinfo/
total 32
 8 -rw-rw-r--. 1 root root 1728 May  3 15:02 Dockerfile-ubi8-minimal-8.8-860
16 -rw-rw-r--. 1 root root 8711 Jun 19 14:28 Dockerfile-ubi8-openjdk-17-runtime-1.16-1.1687182770
 8 drwxr-xr-x. 1 root root 4096 Jun 19 14:31 content_manifests

[jboss@2746c3b882d6 ~]$ cat /root/buildinfo/Dockerfile-ubi8-openjdk-17-runtime-* | grep build-date
LABEL "release"="1.1687182770" "distribution-scope"="public" "vendor"="Red Hat, Inc." "build-date"="2023-06-19T14:12:15" "architecture"="x86_64" "vcs-type"="git" "vcs-ref"="3aa842acd0430ce1e0a6ba3219d036dd6ec6337b" "url"="https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/openjdk-17-runtime/images/1.16-1.1687182770"


```
