### ISSUE TITLE
s2i builds do not empty /tmp before shipping image

### ISSUE THREAD

**Issue by CoaxVex** [rh-openjdk/redhat-openjdk-containers#38]
Source 2 image builds using the openjdk image do not seem to empty /tmp before flattening and shipping the image. This results in the application source code, which is copied to /tmp/src, to be included in the image.
If you specify a reference in openshift for the git source, this does a full clone of the repository, which can lead to images that are larger than they should be.

Is there a way to have /tmp emptied? Or is the right approach to override the assemble script and do it yourself?

I'm building on OpenShift 3.7 with redhat-openjdk-18/openjdk18-openshift:1.5.

**Comment by jmtd** [comment]
Thanks for your report. I remember that we noticed this some time ago, and I cannot remember if we deliberately left the stuff in /tmp or not. It may be that this relates to incremental build support in some way.

**Comment by jmtd** [comment]
Confirmed. The src is still in `/tmp/src`, and the maven artefacts are in `/tmp/artefacts`, even if the s2i build was not incremental.
Reported at https://issues.redhat.com/browse/OPENJDK-84

**Comment by jmtd** [comment]
https://github.com/jboss-openshift/cct_module/pull/375

**Comment by jmtd** [comment]
Closing this, because the fix is merged into `develop` (https://github.com/jboss-container-images/openjdk/blob/develop/modules/s2i/core/bash/artifacts/opt/jboss/container/s2i/core/s2i-core#L148) even though we haven't shipped the fix in a binary image yet. (It's scoming!)
