### ISSUE TITLE
ubi8-openjdk-11 JAVA_OPTS_APPEND not working

### ISSUE THREAD

**Issue by simonhir** [rh-openjdk/redhat-openjdk-containers#390]
Hi,
since the newest version 1.17 our `JAVA_OPTS_APPEND` are not used for startup.
When moving them to `JAVA_OPTIONS` everything works.

Following the different startup logs from two Pods built with 1.17 and 1.16 but with the same `JAVA_OPTIONS` and `JAVA_OPTS_APPEND`:
1.17
```
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec -a "java" java -Djavax.net.ssl.trustStore=/mnt/cacerts/cacerts-asd -Dfile.encoding=UTF-8 -cp "." -jar /deployments/spring-boot-application.jar
```
1.16
```
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec -a "java" java -Djavax.net.ssl.trustStore=/mnt/cacerts/cacerts-asd -Dfile.encoding=UTF-8 -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=300m -XX:+ExitOnOutOfMemoryError -Djavax.net.ssl.trustStore=/mnt/cacerts/cacerts-asd -Dfile.encoding=UTF-8 -javaagent:/appd/javaagent.jar -Dappdynamics.jvm.shutdown.mark.node.as.historical=true -Dappdynamics.http.proxyHost=internet-proxy-server.asd.de -Dappdynamics.http.proxyPort=80 -cp "." -jar /deployments/asd-restapi-0.2.0-SNAPSHOT.jar
```

After looking over the startup file we noticed following change which looks a bit suspicious:
https://github.com/jboss-container-images/openjdk/commit/c78dee442686056c04a667068c3362aa97eb3565#diff-e38c49939e67e17236485b64a7afc257e6b78a92f42e9654aac965f225fb00a4R156
In my opinion there is a typo for `${JAVA_OPTS-$(run_java_options)...}` and should be more like `"${JAVA_OPTS}-$(run_java_options)"` or a `:` is missing and so `${JAVA_OPTS:-$(run_java_options)...}`.

Thanks in advance

**Comment by jmtd** [comment]
The intended semantics for `JAVA_OPTS_APPEND` is for user-provide options to be appended to those calculated by our run scripts. `JAVA_OPTS` is intended to override and replace any options calculated by our run scripts.

What are you defining `JAVA_OPTS_APPEND` to? (and can you clarify that you are not also defining `JAVA_OPTS` at the same time)?

Can I also clarify that you are running the run script from the image? The issue text implies so (`INFO exec -a "java"...`) but the Dockerfiles in this repo are overriding `CMD`: https://github.com/search?q=repo%3Ait-at-m%2Fdigiwf-core%20ubi8%2Fopenjdk-11&type=code

**Comment by jmtd** [comment]
> In my opinion there is a typo for "${JAVA_OPTS-$(run_java_options)...} and should be more like "${JAVA_OPTS}-$(run_java_options)" or a : is missing and so "${JAVA_OPTS:-$(run_java_options)...}.


`${JAVA_OPTS-...}` is a [bash string expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html). It is intended to mean "if `JAVA_OPTS` is unset, the stuff after the dash is taken for the value`. So if you set JAVA_OPTS (even to the empty string), the remainder is ignored. (this includes JAVA_OPTS_APPEND).

If we add the colon, the difference would be setting JAVA_OPTS="" would not override the calculated parameters.

**Comment by simonhir** [comment]
> What are you defining JAVA_OPTS_APPEND to? (and can you clarify that you are not also defining JAVA_OPTS at the same time)?

We only define `JAVA_OPTIONS` and `JAVA_OPTS_APPEND`. See following output from pod console.
```
sh-4.4$ echo $JAVA_OPTS

sh-4.4$ echo $JAVA_OPTIONS
-Djavax.net.ssl.trustStore=/mnt/cacerts/cacerts-asd -Dfile.encoding=UTF-8
sh-4.4$ echo $JAVA_OPTS_APPEND
-Djavax.net.ssl.trustStore=/mnt/cacerts/cacerts-asd -Dfile.encoding=UTF-8 -javaagent:/appd/javaagent.jar -Dappdynamics.jvm.shutdown.mark.node.as.historical=true -Dappdynamics.http.proxyHost=internet-proxy-server.asd.de -Dappdynamics.http.proxyPort=80
```

Based on your description when to use what var i only set `JAVA_OPTS_APPEND` and removed `JAVA_OPTIONS` then every thing works also.

What we think now is that our `JAVA_OPTIONS` were used for the `JAVA_OPTS` value. (Probably because our start `CMD` uses `JAVA_OPTIONS`).
So our solution would be to only use `JAVA_OPTS_APPEND`.

Sorry for the misinterpreted bug that looked for us like a "breaking change" because of strangely set java vars and thanks for the explanations.

**Comment by jerboaa** [comment]
@simonhir Please see this doc for a description of `JAVA_OPTIONS` (and what it does): https://jboss-container-images.github.io/openjdk/ubi8/ubi8-openjdk-11.html

It's a deprecated value and is replaced with `JAVA_OPTS` in UBI 9 images. Please move away from using it (which is what you seem to be doing now). Only using `JAVA_OPTS_APPEND` is the right move.

**Comment by jmtd** [comment]
> Sorry for the misinterpreted bug that looked for us like a "breaking change" because of strangely set java vars and thanks for the explanations.

No problem. It's technically a regression fix (the behaviour of JAVA_OPTS and JAVA_OPTIONS changed from this to the 1.16 behaviour years ago by accident, possibly around1.3...) but I'm sorry the recent change caused problems.
