### ISSUE TITLE
consolidate destination path for image scripts

### ISSUE THREAD

**Issue by jmtd** [rh-openjdk/redhat-openjdk-containers#396]
https://github.com/jboss-container-images/openjdk/blob/ba6fb988aa04382c7ee7e374bf1309e758c82cac/templates/jlink/Dockerfile#L22C1-L22C1

You've had to add a separate COPY to cover logging.sh since it is copied to a different place to the run script. There will be other missing scripts, too (e.g. proxy). I'd like to audit, and tidy up, the location that all scripts are copied to in the images, which will have the side-effect of meaning we can probably reduce the number of distinct COPY instructions needed in the Dockerfile (ideally down to one).

Here's my initial attempt to list all the scripts that are copied into the image and where. Note that some of these modules are builder-image specific, others apply to both builder and runtime; some (the JDK-version-specific modules) are mutually exclusive in the context of a single image:

```
$ find modules/ -type d -name artifacts | while read d; do echo $d:; find $d -type f | sed 's#^.*artifacts/#    #'; done
modules/jvm/artifacts:
    opt/jboss/container/java/jvm/java-default-options
    opt/jboss/container/java/jvm/debug-options
modules/jre/8/artifacts:
    opt/jboss/container/openjdk/jre/jvm-options
modules/jre/11/artifacts:
    opt/jboss/container/openjdk/jre/jvm-options
modules/jre/17/artifacts:
    opt/jboss/container/openjdk/jre/jvm-options
modules/jdk/8/artifacts:
    opt/jboss/container/openjdk/jdk/jvm-options
modules/jdk/11/artifacts:
    opt/jboss/container/openjdk/jdk/jvm-options
modules/jdk/17/artifacts:
    opt/jboss/container/openjdk/jdk/jvm-options
modules/run/artifacts:
    opt/jboss/container/java/run/run-env.sh
    opt/jboss/container/java/run/run-java.sh
modules/util/logging/artifacts:
    opt/jboss/container/util/logging/logging.sh
modules/proxy/artifacts:
    opt/jboss/container/java/proxy/proxy-options
    opt/jboss/container/java/proxy/parse-proxy-url.sh
    opt/jboss/container/java/proxy/translate-no-proxy.sh
modules/s2i/bash/artifacts:
    opt/jboss/container/java/s2i/maven-overrides
    opt/jboss/container/java/s2i/s2i-core-hooks
    opt/jboss/container/java/s2i/maven-s2i-overrides
    usr/local/s2i/usage
    usr/local/s2i/run
    usr/local/s2i/assemble
modules/s2i/run/artifacts:
    opt/jboss/container/java/s2i/maven-overrides
    opt/jboss/container/java/s2i/s2i-core-hooks
    opt/jboss/container/java/s2i/maven-s2i-overrides
modules/s2i/core/artifacts:
    opt/jboss/container/s2i/core/s2i-core
modules/maven/default/artifacts:
    opt/jboss/container/maven/default/maven.sh
    opt/jboss/container/maven/default/jboss-settings.xml
modules/maven/module/artifacts:
    maven.module
modules/maven/s2i/artifacts:
    opt/jboss/container/maven/s2i/maven-overrides
    opt/jboss/container/maven/s2i/maven-s2i
    usr/local/s2i/save-artifacts
    usr/local/s2i/assemble
```

Actually looking at this list we could probably reduce most of the copies down to a single `COPY /opt/jboss`.

**Comment by jhuttana** [comment]
Thanks for this suggestion. Instead of COPY /opt/jboss/ is it good to have COPY /opt/jboss/container ?

**Comment by jmtd** [comment]
> Thanks for this suggestion. Instead of COPY /opt/jboss/ is it good to have COPY /opt/jboss/container ?

Yeah that would work too, and might be a bit safer, perhaps if a downstream image puts something unrelated in `/opt/jboss`.
