### ISSUE TITLE
test coverage for user-provided run-env.sh

### ISSUE THREAD

**Issue by jmtd** [rh-openjdk/redhat-openjdk-containers#399]
https://github.com/jboss-container-images/openjdk/blob/d39eac69f37f4090b89103117fcddbbf24ad680c/modules/run/artifacts/opt/jboss/container/java/run/run-java.sh#L102

The above code seems to suggest that a script named run-env.sh placed in `$JAVA_APP_DIR` (which defaults to `/deployments`) is sourced by the run script prior to launching java.

I don't think we have any behave test coverage for this feature. Before we make changes to this code area, I would like to have coverage to first test that this actually works, and later it remains working after any future refactoring (e.g. in #397 )

The test will need to perform an S2I build of a prepared application source, such that after the build, there is a `run-env.sh` script in `$JAVA_APP_DIR` which does something we can easily detect after starting the resulting container. A good candidate might be to set `JAVA_APP_NAME=someCustomString`, which *should* cause the final process name to be changed and that to be easily detected in container logs.

The prepared application source will need to live somewhere. We used to use the following repository as a source of test application sources: https://github.com/jboss-openshift/openshift-quickstarts but we archived it this year for various reasons. See #400 for further details of that (which effectively blocks this issue)

**Comment by jhuttana** [comment]
I am just trying to figure out which file the test goes into and how it looks. 
I guess the test goes into [tests/features/java/runtime.feature](https://github.com/jboss-container-images/openjdk/blob/ubi9/tests/features/java/runtime.feature)?
and looks like this :

@ubi9
  Scenario: Check JAVA_APP_NAME is set to final process name
    Given container is started with env
    | variable         | value   |
    | JAVA_APP_NAME    | someCustomString |
  Then container log should contain JAVA_APP_NAME=someCustomString

?

**Comment by jmtd** [comment]
> I am just trying to figure out which file the test goes into and how it looks.

The test structure is a bit broken/unclear/undefined, so don't worry about it too much. We need to clean it up, I have raised a JIRA about that with a suggested approach ([OPENJDK-2177](https://issues.redhat.com/browse/OPENJDK-2177)) but in the meantime this shouldn't block adding more tests.

> I guess the test goes into [tests/features/java/runtime.feature](https://github.com/jboss-container-images/openjdk/blob/ubi9/tests/features/java/runtime.feature)?

That file is supposed to be for tests appropriate for the runtime images, but I think to test this feature we will need to do an S2I build which means using the builder images. `tests/features/java/java_s2i.feature` might be a better home.

>  and looks like this :

Take a look at one of the tests that use S2I in `tests/features/java/java_s2i.feature`. The "Given" line will have to be something like `    Given s2i build https://github.com/jboss-openshift/openshift-examples from spring-boot-sample-simple/target`, except, we will need a new URI with an appropriately-prepared application source for the test.

>  Then container log should contain JAVA_APP_NAME=someCustomString

Try running an existing openjdk container with JAVA_APP_NAME=somethingUnique
 and look at its output to choose an appropriate string for the test.

**Comment by jmtd** [comment]
Since #397 targets `jlink-dev`, I've merged it and not considered it blocked by this work (although this work should block eventually merging the `jlink-dev` branch back to `ubi9`).

**Comment by jmtd** [comment]
promoted to https://issues.redhat.com/browse/OPENJDK-2200

**Comment by jhuttana** [comment]
> The test structure is a bit broken/unclear/undefined, so don't worry about it too much. We need to clean it up, I have raised a JIRA about that with a suggested approach ([OPENJDK-2177](https://issues.redhat.com/browse/OPENJDK-2177)) but in the meantime this shouldn't block adding more tests.

+1

> 

> That file is supposed to be for tests appropriate for the runtime images, but I think to test this feature we will need to do an S2I build which means using the builder images. `tests/features/java/java_s2i.feature` might be a better home.
> 

How about tests/features/java/openjdk_s2i.feature ? as the tests in that file are using the application source from https://github.com/jboss-openshift/openshift-quickstarts which we are planning to move to https://github.com/jboss-openshift/openjdk-test-applications and the sample application for our multistage build is also quarkus-getting-started.

> 
> Take a look at one of the tests that use S2I in `tests/features/java/java_s2i.feature`. The "Given" line will have to be something like ` Given s2i build https://github.com/jboss-openshift/openshift-examples from spring-boot-sample-simple/target`, except, we will need a new URI with an appropriately-prepared application source for the test.
> 

Sure

> 
> Try running an existing openjdk container with JAVA_APP_NAME=somethingUnique and look at its output to choose an appropriate string for the test.

Yes I tried that 
```
$ podman run --rm -it -e  JAVA_APP_NAME='someUniqueString' localhost/ubi9-micro-jlink-jre:latest
INFO exec -a "someUniqueString" java  -cp "." -jar /deployments/getting-started-1.0.0-SNAPSHOT-runner.jar 
INFO running in /deployments
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-09-26 17:48:49,238 INFO  [io.quarkus] (main) getting-started 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.0.3.Final) started in 0.531s. Listening on: http://0.0.0.0:8080
2023-09-26 17:48:49,254 INFO  [io.quarkus] (main) Profile prod activated. 
2023-09-26 17:48:49,254 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy-reactive, smallrye-context-propagation, vertx]
^C2023-09-26 17:48:53,874 INFO  [io.quarkus] (main) getting-started stopped in 0.016s
```

So the serach string will be :  log should contain INFO exec -a "someUniqueString" java  -cp

**Comment by jmtd** [comment]
> So the serach string will be : log should contain INFO exec -a "someUniqueString" java -cp

Yes that would work.

We would need to ensure a) the test did not define `JAVA_APP_NAME` itself; b)  if the application source contained a `.s2i/environment` file containing `JAVA_APP_NAME=someCustomString`.

#400 should block merging this, but hopefully doesn't block continuing to work on it. You can fork the existing repo (or the quarkus-quickstarts repo) to your personal github space and then reference that in a test to get going (we have at least one test already which references my fork, https://github.com/jmtd/openshift-quickstarts, and another which references https://github.com/jerboaa/quarkus-quickstarts; these can all eventually be replaced with a new repo in #400)
