### ISSUE TITLE
need a new home for application sources used in tests

### ISSUE THREAD

**Issue by jmtd** [rh-openjdk/redhat-openjdk-containers#400]
Many of the tests in `tests/behave`  reference specially prepared application sources which live in this repository:
https://github.com/jboss-openshift/openshift-quickstarts

For various reasons we had to archive that repository earlier this year. We can still reference the existing application sources, but we cannot update them or add new ones.

We should analyze which of the application sources in that repository are referenced in our behave tests (it's only a sub-set); and copy those to a new repository, then update the tests.

One question is where should that new repository live. One possibility would be jboss-openshift/openjdk-test-applications

**Comment by jmtd** [comment]
promoted to https://issues.redhat.com/browse/OPENJDK-2199

**Comment by jhuttana** [comment]
I have analyzed and listed the behave test files that use application sources from https://github.com/jboss-openshift/openshift-quickstarts 
```
$ grep -inr "jboss-openshift/openshift-quickstarts"
arq/src/test/resources/openjdk18-mysql-persistent-s2i.json:67:            "value": "https://github.com/jboss-openshift/openshift-quickstarts",
arq/src/test/resources/openjdk18-mysql-s2i.json:67:            "value": "https://github.com/jboss-openshift/openshift-quickstarts",
arq/src/test/resources/openjdk18-postgresql-persistent-s2i.json:67:            "value": "https://github.com/jboss-openshift/openshift-quickstarts",
arq/src/test/resources/openjdk18-postgresql-s2i.json:67:            "value": "https://github.com/jboss-openshift/openshift-quickstarts",
arq/src/test/resources/openjdk18-web-https-s2i.json:73:            "value": "https://github.com/jboss-openshift/openshift-quickstarts",
features/java/java_s2i_inc.feature:7:    Given s2i build https://github.com/jboss-openshift/openshift-quickstarts from undertow-servlet
features/java/java_s2i_inc.feature:12:    Given s2i build https://github.com/jboss-openshift/openshift-quickstarts from undertow-servlet with env and incremental
features/java/openjdk_s2i.feature:6:    Given s2i build https://github.com/jboss-openshift/openshift-quickstarts from undertow-servlet
features/java/ports.feature:6:    Given s2i build https://github.com/jboss-openshift/openshift-quickstarts from undertow-servlet
features/java/runtime.feature:6:    Given s2i build https://github.com/jboss-openshift/openshift-quickstarts from undertow-servlet
features/java/runtime.feature:73:    Given s2i build https://github.com/jboss-openshift/openshift-quickstarts from undertow-servlet
```
Looking at the above output we can conclude that our existing test  cases are referencing application source from "undertow-servlet" which we have to move to new repository  jboss-openshift/openjdk-test-applications.
But I am not sure its possible to create the suggested repository  jboss-openshift/openjdk-test-applications  (which looks like https://github.com/jboss-openshift/openjdk-test-applications) with permissions I have!
Or only the contributors will have enough permissions to create repositories under that namespace/organization? (I am not a contributor there)

**Comment by jmtd** [comment]
> But I am not sure its possible to create the suggested repository jboss-openshift/openjdk-test-applications (which looks like https://github.com/jboss-openshift/openjdk-test-applications) with permissions I have!

Do you have permission to create in the jboss-container-images  organisation instead?

**Comment by jmtd** [comment]
I will need to audit all of the jboss-container-images permissions at some point in the future.

In the meantime, I've created https://github.com/jboss-container-images/openjdk-test-applications

it's empty :-)

Please try raising a PR for that repository to add the quickstarts you identified that we need from https://github.com/jboss-openshift/openshift-quickstarts

Thank you!

**Comment by jhuttana** [comment]
Sure Jon I will do that :)
