### ISSUE TITLE
tests using undertow-servlet are failing due to cert issues

### ISSUE THREAD

**Issue by jmtd** [rh-openjdk/redhat-openjdk-containers#431]
The failing tests are all the ones that use the undertow-servlet quickstart, and the failure reason is to do with certificates relating to one of the redhat maven repositories:

> Could not transfer artifact org.jboss.logmanager:jboss-logmanager:pom:2.0.3.Final-redhat-1 from/to redhat-ga-repository (https://maven.repository.redhat.com/ga/): transfer failed for https://maven.repository.redhat.com/ga/org/jboss/logmanager/jboss-logmanager/2.0.3.Final-redhat-1/jboss-logmanager-2.0.3.Final-redhat-1.pom: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

_Originally posted by @jmtd in https://github.com/jboss-container-images/openjdk/issues/430#issuecomment-1880762953_

**Comment by jhuttana** [comment]
There was an email with sub: "The Red Hat Maven Repo is not accessible from any project due to a certificate issue" two days back. Now that issue is  fixed. To verify that I have run the tests locally and they are passing.

**Comment by jmtd** [comment]
Ah ok, thank you. I'll keep an eye on the next set of test runs and see if anything still crops up.
