### ISSUE TITLE
Image without openjdk (jlink)

### ISSUE THREAD

**Issue by ciis0** [rh-openjdk/redhat-openjdk-containers#503]
Are there intentions providing (additional) openjdk runtime images with only the entrypoint scripts, without openjdk, for projects which "build" their own/custom openjdk using jlink?

I suppose it likely is already possible by removing the current openjdk from the image and adding the jlink openjdk, but that would increase transferred layer data unnecessarily.

**Comment by jmtd** [comment]
Hi, we (OpenJDK) have no plans to produce an image without OpenJDK in it. But I am open to ideas for alternative ways to package or distribute the run script.
