### ISSUE TITLE
rename project/repo to include "s2i" ?

### ISSUE THREAD

**Issue by vorburger** [rh-openjdk/redhat-openjdk-containers#56]
@jmtd I find it curious that this repo/project is named "openjdk" (under jboss-container-images) when, in fact, it's not (just) an OpenJDK container image, but an S2I builder image (based on OpenJDK). Is it too late to rename this to something like s2i-openjdk or openjdk-s2i ? And perhaps (now or in the future) have a separate repo/project named "openjdk" for an image with the community version of a CentOS/Fedora OpenJDK container, automatically kept up-to-date, but without the S2I stuff. Just a thought.

**Comment by jorgemoralespou** [comment]
+1
We need non-s2i variants, so making clear when images are s2i makes sense.

**Comment by jmtd** [comment]
There are some conversations going on about a non-S2I (and non JDK) image variant, but it's not clear what the spec of that will be (should it include JDK? should it include Maven?), and it's likely that it would co-exist in this repository perhaps via an overrides file or in a separate branch. So it seems premature to rename this repository until those details are worked out; also, at least if/until that image exists, this is the only image being produced by the RH OpenJDK team. So the name seems appropriate for the current state of the world.

**Comment by vorburger** [comment]
> There are some conversations going on about a non-S2I (and non JDK) image variant 

anything you can link to?

> but it's not clear what the spec of that will be (should it include JDK? should it include Maven?), 

A new TBD OpenJDK base container image (non-S2I) certainly SHOULD include JDK - otherwise what is in it?  Or do you mean whether it should include the JDK vs. the JRE? My view on that would be that we should, ideally, offer both IMHO.

Such a base image should certainly NOT include Maven IMHO - that's the role of this S2I image? And not everyone builds with Maven (Gradle #64), or with whatever fixed version of Maven you would choose (#68).

**Comment by jmtd** [comment]
> anything you can link to?

I don't think so.

> Or do you mean whether it should include the JDK vs. the JRE? My view on that would be that we should, ideally, offer both IMHO.

Yes that. One question for a JRE only image (and caveat: the terminology/distinction between JRE/JDK is going away so we should apparently avoid it, but not sure what to use instead): how does the user use it with their code / get their code into a derivative image?

**Comment by vorburger** [comment]
> Yes that. One question for a JRE only image (and caveat: the terminology/distinction between JRE/JDK is going away so we should apparently avoid it, but not sure what to use instead): 

Huh? If it's branding/naming crap, just use e.g JRE = _Runtime_ Image & JDK = (non-S2I) _Build Time_ ...

> how does the user use it with their code / get their code into a derivative image?

Erm... how do you mean? One can esily just _FROM_ such an image, like the whole (non-S2I) world does everywhere... So e.g. in https://github.com/fabric8io-images/s2i/tree/master/java/examples/maven, but a `Dockerfile` like so:

```
FROM s2i-java-11

COPY target/HttpServer-example-1.0-SNAPSHOT.jar /deployments/

CMD java -jar /deployments/HttpServer-example-1.0-SNAPSHOT.jar

```
and then:

    docker build . -t test
    docker run --rm -it test

The use of fabric8io-images/s2i is irrelevant here of course, this is NOT S2I anymore (which is what we are discussed here now, I think), I've just used it because it was the fastest way for me to illustrate the point - hope that makes sense.

Or did I misunderstand your question?

**Comment by jmtd** [comment]
> Huh? If it's branding/naming crap, just use e.g JRE = _Runtime_ Image & JDK = (non-S2I) _Build Time_ ...

It's a change in the way that Java/OpenJDK are being built/prepared/marketed/blah. But using "builder" and "runtime" also dovetails nicely with other things in the container universe.

> how do you mean? One can esily just _FROM_ such an image,

That's exactly what I mean, yes. So what exactly is the runtime image, then? If someone is writing this already:

```
FROM s2i-java-11
COPY target/HttpServer-example-1.0-SNAPSHOT.jar /deployments/
CMD java -jar /deployments/HttpServer-example-1.0-SNAPSHOT.jar
```

Is there any point in a runtime image when it would trivially amount to the extra 3 lines here

```
FROM rhel7 # or centos, or…
USER 0
RUN yum install -y java-11-openjdk-11 && rpm -q java-11-openjdk
USER 185 # whatever
COPY target/HttpServer-example-1.0-SNAPSHOT.jar /deployments/
CMD java -jar /deployments/HttpServer-example-1.0-SNAPSHOT.jar
```

**Comment by vorburger** [comment]
> So what exactly is the runtime image, then? If someone is writing this already:
> Is there any point in a runtime image when it would trivially amount to the extra 3 lines here

good point, but personally I do think there is value in having this.. here are a few of the reasons why:

* many people probably don't really understand best practices 
** like `USER 0` vs. `USER 185` 
** `yum clean all`
** [the urandom thing](https://github.com/fabric8io-images/s2i/blob/f37692ce45ba40e425bec5077726085195854fe1/java/images/centos/Dockerfile#L51)
* https://hub.docker.com/_/openjdk is pretty popular - and has everything but CentOS/Fedora - shame?
* https://github.com/GoogleContainerTools/distroless is really popular - I'd love to have sth like that, as one of the variant of such a base image, in the future
* security updates... the base image should be rebuilt whenever there are OpenJDK RPM updates

Let's move this discussion to new issue #72 ?
