### ISSUE TITLE
artefacts in RHEL7-based images prevent easily building the images

### ISSUE THREAD

**Issue by vorburger** [rh-openjdk/redhat-openjdk-containers#57]
I'm interested in being able to locally build this project myself (for #51) but still failing miserably.

Originally #48, but currently not even get that far anymore.

I'll open more specific issues, and link them here; I'l close this issue when I can actually locally build this project easily.

**Comment by vorburger** [comment]
https://github.com/jboss-container-images/openjdk/issues/48

https://github.com/cekit/cekit/issues/380

https://github.com/cekit/cekit/issues/381

**Comment by vorburger** [comment]
#58

#59

#60

**Comment by vorburger** [comment]
#63

**Comment by jmtd** [comment]
Hi @vorburger , I don't think you are still interested in using cekit/building these images (correct me if I'm wrong), but I didn't want to close off this issue until the problems had been resolved. All the linked issues and PRs are closed or merged now except for one — #58 — and there's still a problem there to fix (although the PR isn't sufficient). Therefore, I am going to re-title this issue to describe the problem that #58 tries to address. Please let me know if you have any objections.

**Comment by jmtd** [comment]
To expand on the (new) issue title: The RHEL7-based images require Prometheus and Jolokia artefacts to be sourced somehow as part of the image build process. This happens mostly automatically when building in a Red Hat internal environment but requires the user to independently source the artefacts and install them in their local cekit cache for other cases, which is awkward.

This was resolved for the RHEL8-based images by moving the artefacts into RPMs.

**Comment by vorburger** [comment]
> Hi @vorburger , I don't think you are still interested in using cekit/building these images (correct me if I'm wrong)

If it helps for your prioritization and planning, I'm happy to confirm that I have indeed sailed on (very far actually), and therefore no longer have any interest in this space. Feel free close issues or do what you deem best. I'm unsubscribing from Notifications of such issues when I get emails about updates.

All the best.

**Comment by jmtd** [comment]
Thanks — good luck in your new adventure (1Y late :))
