### ISSUE TITLE
Community image CentOS JDK 11 cannot be built as documented

### ISSUE THREAD

**Issue by vorburger** [rh-openjdk/redhat-openjdk-containers#59]
https://github.com/jboss-container-images/openjdk/blob/d908decf65a30bc179f29d25286daf5ff630696e/README.adoc#centos-jdk-11 documentation says that I should be able to build Community image CentOS JDK 11 as follows:

    cekit --overrides-file=centos7-jdk11-overrides.yaml build

This currently does not work, and fails with:

    ...
    ERROR    The md5 computed for the 'target/image/hawkular-javaagent-1.0.1.Final-redhat-2-shaded.jar' file ('1f55173d84e4ac52d0ee542e251d8b02') doesn't match the 'f97f623e5b614a7b6d1eb5ff7158027b' value
    ...
    ERROR    Error copying resource: 'hawkular-javaagent'. See logs for more info.

I gather it would need a similar hack like #58, but it seems one can only specify one `--overrides-file` so how do you want to handle this?

**Comment by vorburger** [comment]
> but it seems one can only specify one `--overrides-file` so how do you want to handle this?

I guess one solution would be to add those `artifacts` overrides from the `overrides.yaml` in #58 to the `centos7-jdk11-overrides.yaml` .. but that would duplicate those GAVs, which seems sub-optimal, I'm hoping you can think of a better solution.

**Comment by kadel** [comment]
I just hit the same issue. Is there a way to work around this? Sadly don't know much about cekit :-(

**Comment by vorburger** [comment]
> I just hit the same issue. Is there a way to work around this? Sadly don't know much about cekit :-(

you could always use https://github.com/fabric8io-images/s2i/ in the mean time... ;-)

**Comment by kadel** [comment]
> > I just hit the same issue. Is there a way to work around this? Sadly don't know much about cekit :-(
> 
> you could always use https://github.com/fabric8io-images/s2i/ in the mean time... ;-)

great :-(
fish-pepper  yet another way to build an image

**Comment by jmtd** [comment]
> but it seems one can only specify one `--overrides-file`

You can specify more than one, at least with cekit 2.x.

I've just tried reproducing with cekit 2.2.6 and the build worked. The artefact in question, and its sum, are specified in the external [cct_module](https://github.com/jboss-openshift/cct_module) (specifically `jboss/container/hawkular/bash/module.yaml`). These haven't changed in a while.

I think the most likely explanation is a transient problem fetching the artefact. The file that was fetched and has the wrong checksum most likely contains the text "HTTP/1.0 404 not found" or something similar. If either of you have the build tree from the failed build  around still, can you look at the artefact in `target/image` and see how big it is? If it's really small it's worth checking whether it's just error text.

If that's the case, then I'd argue this is a cekit bug and it should report HTTP errors for artefact fetching more clearly.

**Comment by jmtd** [comment]
We've removed the CentOS image descriptors now, so I'm closing bugs that are specific to those. Watch this space for a (better?) solution for the community story!
