### ISSUE TITLE
Avoid requiring a weird ~/.cekit/config with `dummy-url` (which cause a WARNING)

### ISSUE THREAD

**Issue by vorburger** [rh-openjdk/redhat-openjdk-containers#60]
I learnt in #48 that, quote:

> To workaround the issue, you can create a `~/.cekit/config` file which contains:

```ini
[repositories]
jboss-os=dummy-url
jboss-rhscl=dummy-url
```

this does seem to do the trick, but:

1. it's weird that such a work around is needed at all?

2. this is not currently documented on the README ...

3. this seems to lead to the following confusing message: `WARNING  The way of defining repository 'jboss-os' is deprecated. Convert it to an URL based repository object. Consult Cekit docs, for more details.
`

**Comment by jmtd** [comment]
I think this is "fixed" as a side-effect of removing the CentOS-flavoured image definitions (which we never built or published, alas).
