### ISSUE TITLE
test_metrics() from fabric8's test.sh fails with centos/openjdk-8-centos7

### ISSUE THREAD

**Issue by vorburger** [rh-openjdk/redhat-openjdk-containers#62]
For #51 I've [played with a first test](https://github.com/fabric8io-images/s2i/compare/master...vorburger:issue-51_test-jboss-container-images_openjdk), and it failed when it tried to GET `/metrics` ...

I was just wondering if this was expected in this image?

**Comment by vorburger** [comment]
oh... you use `/jolokia` instead of `/metrics` in this image, and run it on 8778 instead of 9779 huh?

But even after fixing that, the curl in `test_metrics()` in our [test.sh](https://github.com/fabric8io-images/s2i/blob/master/test.sh) still fails, now with `curl: (52) Empty reply from server` (instead of the initial `curl: (56) Recv failure: Connection reset by peer` due to wrong URL & port) ...

**Comment by jmtd** [comment]
Is this testing against centos/openjdk-11-centos7 ? I'm unsure of the status of jolokia (and hawkular) in the 11-flavour images. There's at least these two known problems: https://issues.jboss.org/browse/CLOUD-3018 (⇒ https://github.com/rhuss/jolokia/issues/394) and https://issues.jboss.org/browse/CLOUD-3054

**Comment by vorburger** [comment]
> Is this testing against centos/openjdk-11-centos7 ? 

no, with a (locally built) centos/openjdk-8-centos7 .. (I haven't been able to build 11 yet, due to #59.)

do the tests here test the metrics, similar to test.sh does over in our other project? (but NB #63)

**Comment by jmtd** [comment]
There appears to be very limited testing at the moment. we test [jolokia made it into the image, and what version](https://github.com/jboss-container-images/openjdk/blob/e09f953b533f66453dacdacffd8228e778721e78/tests/features/java/jolokia.feature#L30), and that we get [the jolokia banner at startup](https://github.com/jboss-container-images/openjdk/blob/7fedb02bd7ae553ed59a3d180ab5db990e35ea32/tests/features/java/runtime.feature#L22), and not much else.

**Comment by jmtd** [comment]
I think this is because [test.sh assumes http](https://github.com/fabric8io-images/s2i/blob/master/test.sh#L42) but we [default to https](https://github.com/jboss-openshift/cct_module/blob/1ff1d9637979b1d0b116f247640f5330b20a7a45/jboss/container/jolokia/api/module.yaml#L20)

If you wanted to confirm you could try starting the container with the environment variable `AB_JOLOKIA_HTTPS=false`
