### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by vorburger** [rh-openjdk/redhat-openjdk-containers#65]
We could improve the README of this project... I'll outline a possible future structure, for discussion.

**Comment by vorburger** [comment]
https://github.com/jboss-container-images/openjdk/compare/develop...vorburger:issue-65_better-README

**Comment by jmtd** [comment]
Those look like very good suggestions

**Comment by vorburger** [comment]
> Those look like very good suggestions

then how about #66, as a first step?

**Comment by vorburger** [comment]
and #69, as a second step?

**Comment by jmtd** [comment]
Closing as the related PRs are closed, please re-open if you don't feel this has been addressed!
