### ISSUE TITLE
Long term solution to build CE images without overrides

### ISSUE THREAD

**Issue by vorburger** [rh-openjdk/redhat-openjdk-containers#67]
from #48:

> Note, using this method, the files in the image will still be named with _-redhat-_ in them, but they will be the community versions (you can verify by expanding the jars and looking at the META-INF/maven/... files).
> 
> @jmtd, if we're going to make the default versions of the image.yaml file community oriented, we should probably do the same with the upstream modules (jolokia, hawkular, jmx_exporter). That said, there's probably some work to be done in cekit to help ensure we're using the "proper" file names for these types of resources (e.g. jolokia-jvm-1.5.0-agent.jar instead of jolokia-jvm-1.5.0.redhat-1-agent.jar). @goldmann, @dbecvarik, you're probably interested in this as well, from a cekit perspective.

from #58 :

> Putting this in these image sources here would be a short-term solution, because the problem is really over in [cct_modules](https://github.com/jboss-openshift/cct_module), where the artefact definitions are (e.g. https://github.com/jboss-openshift/cct_module/blob/master/jboss/container/jolokia/bash/module.yaml), as @rcernich says in #48 , we probably need community variants of the modules that are pulled in by this image, with correct checksums for the community versions.

I'm not familiar enough with Cekit to be able to help with that hands-on myself... :smile: 

Just sayin' to avoid anyone thinking that I'll do this.

**Comment by jmtd** [comment]
We've removed the CentOS image descriptors now, so I'm closing bugs that are specific to those. Watch this space for a (better?) solution for the community story!
