### ISSUE TITLE
Offer new simple OpenJDK non-S2I/Builder base image

### ISSUE THREAD

**Issue by vorburger** [rh-openjdk/redhat-openjdk-containers#72]
new issue to continue the discussion started in the now closed #56 ...

**Comment by jorgemoralespou** [comment]
Agree with @vorburger that a base runtime image should have all the best practices already encoded in it, so that a user would just need to add the jar file.

**Comment by jmtd** [comment]
In practise I think this means going over [cct_module](https://github.com/jboss-openshift/cct_module/) with a razor and figuring out which modules (and bits of modules) should land either side of a runtime/builder divide

**Comment by jmtd** [comment]
See also https://issues.redhat.com/browse/OPENJDK-45

**Comment by jmtd** [comment]
We resolved this with the runtime images, added initially in  #186.
