### ISSUE TITLE
S2I_SOURCE_DEPLOYMENTS_FILTER does not support sub-directories

### ISSUE THREAD

**Issue by vorburger** [rh-openjdk/redhat-openjdk-containers#75]
While working on https://github.com/quarkusio/quarkus-quickstarts/pull/81, I'm using:

    ARTIFACT_COPY_ARGS=-p -r lib/ *-runner.jar

seeing this:

    WARN ARTIFACT_COPY_ARGS is deprecated.  Please use S2I_SOURCE_DEPLOYMENTS_FILTER to specify artifact types and MAVEN_S2I_ARTIFACT_DIRS to specify the build output directories to copy from.

I've therefore attempted to use `S2I_SOURCE_DEPLOYMENTS_FILTER` instead of `ARTIFACT_COPY_ARGS` like this:

    S2I_SOURCE_DEPLOYMENTS_FILTER=*-runner.jar lib/*.jar

as, according to https://github.com/jboss-openshift/cct_module/blob/master/jboss/container/s2i/core/api/README.adoc (which is somewhat hard to find BTW, see #74), it's a _"Space separated list of filters to be applied when copying deployments."_ ...

```
INFO Copying deployments from target to /deployments...
'/tmp/src/target/quarkus-quickstart-1.0-SNAPSHOT-runner.jar' -> '/deployments/quarkus-quickstart-1.0-SNAPSHOT-runner.jar'
Build completed successfully
```

... but this does not work. Upon investigating this, I found that it does not actually copy the `lib/*.jar` (only `*-runner.jar`) - I'm guessing that S2I_SOURCE_DEPLOYMENTS_FILTER does not support sub-directories? It should.

@jmtd @goldmann @rcernich @wdecoste

PS: I'm filing this issue here in this project instead of over in https://github.com/jboss-openshift/cct_module (where `S2I_SOURCE_DEPLOYMENTS_FILTER` seems to actually be implemented) because that project disabled Issues (without any indication its README where to file issues for that project).

**Comment by jmtd** [comment]
Rob Cernich moved off Cloud stuff in December so please avoid tagging him for container issues. (Bill Decoste moved off over a year before that)

> PS: I'm filing this issue here in this project instead of over in https://github.com/jboss-openshift/cct_module (where S2I_SOURCE_DEPLOYMENTS_FILTER seems to actually be implemented) because that project disabled Issues (without any indication its README where to file issues for that project).

Historically this was so that all issue tracking was done via JIRA - back prior to there being any community stuff. The same was true for image repositories (like this one). I've opened up issues for the cct_module repo. Thanks!

**Comment by jmtd** [comment]
raised here https://github.com/jboss-openshift/cct_module/issues/336 thanks @vorburger 

(I couldn't migrate the issue due to the different github organisations)
